malc: Use proper command-line switches processing

diff --git a/malc b/malc
--- a/malc
+++ b/malc
@@ -1,45 +1,104 @@
-#!/bin/sh
+#!/bin/bash
 set -e
 
-if [ -z "$1" ] ; then
-  echo "Usage: $0 [-l] sourcefile.mal [outputexecutable]"
+usage() {
+  cat << EOF
+Usage: $0 [-g] [-l] [-v] -c source_file.mal [-o executable_file]
+
+OPTIONS:
+   -h/-?        Show this message
+   -c FILENAME  Mal source file name
+   -g           Enable debug mode (mark functions as external for clearer
+                stack traces)
+   -l           Keep intermediate LLVM IR filse
+   -o FILENAME  Output executable file name
+   -v           Enable verbose logging
+EOF
+}
+
+log() {
+  [ "$verbose" == yes ] && echo "malc: $@"
+}
+
+keep_llvm=no
+compile_mode=release
+srcfile=
+outfile=
+verbose=no
+
+while getopts "c:ghlo:v?" OPTION ; do
+  case $OPTION in
+    c)
+      srcfile="$(readlink -f $OPTARG)"
+      ;;
+    g)
+      compile_mode=debug
+      ;;
+    h)
+      usage
+      exit 1
+      ;;
+    l)
+      keep_llvm=yes
+      ;;
+    o)
+      outfile="$(readlink -f $OPTARG)"
+      ;;
+    v)
+      verbose=yes
+      ;;
+    ?)
+      usage
+      exit 1
+      ;;
+  esac
+done
+
+if [ -z "$srcfile" ] ; then
+  usage
   exit 1
 fi
 
 bindir=$(readlink -f $(dirname $0))
+if [ -z "${outfile}" ] ; then
+  outfile="$(dirname $srcfile)/$(basename $srcfile .mal)"
+fi
 
 # user overridable
 MAL_TO_LLVM=${MAL_TO_LLVM:-}
 MAL_PREFIX=${MAL_PREFIX:-}
 MAL_IMPL=$(readlink -f ${MAL_IMPL:-$bindir/mal-interpreter/mal})
 
-leave_llvm=no
-if [ "$1" = "-l" ] ; then
-  leave_llvm=yes
-  shift
-fi
-compilemode=release
-if [ "$1" = "-g" ] ; then
-  compilemode=debug
-  shift
-fi
-srcfile="$(readlink -f $1)"
-if [ -n "$2" ] ; then
-  out="$(readlink -f $2)"
-else
-  out="$(dirname $srcfile)/$(basename $srcfile .mal)"
-fi
+log "Source file: $srcfile"
+log "Compile mode: $compile_mode"
+log "Intermediate LLVM IR file: ${outfile}.ll"
 
+# Compile mal to LLVM IR
 if [ -z "$MAL_TO_LLVM" ] ; then
-  ${MAL_PREFIX:+${MAL_PREFIX} }${MAL_IMPL} $bindir/mal-to-llvm.mal $compilemode $bindir $srcfile > $out.ll
+  log "Running mal-to-llvm program: ${MAL_PREFIX:+${MAL_PREFIX} }${MAL_IMPL} $bindir/mal-to-llvm.mal"
+  ${MAL_PREFIX:+${MAL_PREFIX} }${MAL_IMPL} $bindir/mal-to-llvm.mal $compile_mode $bindir $srcfile > "${outfile}.ll"
 else
-  $MAL_TO_LLVM $compilemode $bindir $srcfile > $out.ll
+  log "Running mal-to-llvm program: $MAL_TO_LLVM"
+  $MAL_TO_LLVM $compile_mode $bindir $srcfile > "${outfile}.ll"
 fi
 
-opt -S -O3 $out.ll -o $out.opt.ll
-llc -filetype=obj $out.opt.ll -o $out.o
-gcc -g $out.o -lgc -lreadline -lstdc++ -o $out
-if [ "$leave_llvm" = no ] ; then
-  rm -f $out.ll $out.opt.ll
+# Optimize generated LLVM IR
+log "Optimizing LLVM IR to: ${outfile}.opt.ll"
+opt -S -O3 "${outfile}.ll" -o "${outfile}.opt.ll"
+
+# Compile LLVM IR to object file
+log "Compiling LLVM IR to object file: ${outfile}.o"
+llc -filetype=obj "${outfile}.opt.ll" -o "${outfile}.o"
+
+# Link
+log "Linking executable file: ${outfile}"
+gcc -g "${outfile}.o" -lgc -lreadline -lstdc++ -o "${outfile}"
+
+# Cleanup
+log "Cleaning up"
+if [ "$keep_llvm" = no ] ; then
+  rm -f "${outfile}.ll" "${outfile}.opt.ll"
 fi
-rm -f $out.o
+rm -f "${outfile}.o"
+
+log "Done"
